### ISSUE TITLE
Баг в присвоении 

### ISSUE THREAD

**Issue by PodsolnyX** [Apochromat/codeblock-mobile#2]
![wJg0iZSsUKfhhrSCPC7dWBnrqMRzAaxMh3ZVWt6JMBBZsnp5GAUUdBgmqpUVi8ZrPPRyx45QdspbtzTIt2l-gfHi](https://user-images.githubusercontent.com/101562222/165888385-7dbed7a5-33c0-4e4a-a763-49939a64deb9.jpg)
![yYMHG7EhGuqccqTcJcCNlrrJ_-OkwObpKaOEdlaS3Sb1PyGuQvm2QRpn18SMyrUXr_riPELjgilZp5zBpSZXC_Ce](https://user-images.githubusercontent.com/101562222/165888393-7e485efa-b231-43dd-9079-3d996f7bd5ce.jpg)

**Comment by Apochromat** [comment]
@Millniker, ты это пофиксил или нет?
